### ISSUE TITLE
AWS SES configuration

### ISSUE THREAD

**Issue by memsbdm** [adonisjs/mail#98]
### Package version

9.2.1

### Describe the bug

When configuring SES as mailer, environment variables were not properly set.

Examples: 
- AWS_ACCESS_KEY instead of SES_ACCESS_KEY_ID
- SES_ACCESS_SECRET instead of SES_SECRET_ACCESS_KEY, ...

PR #97 is solving issues. Also in docs the PR #67 is changing the example.

**Comment by Julien-R44** [comment]
I would say we should do the reverse. I mean, change the names of the environment variables

I know this was the case on V5: we had variables SES_ACCESS_KEY_ID etc..
But I've always found it annoying: in general, if you're using SES, you're probably using other AWS services. In particular S3, or SQS. And so I found myself constantly renaming these variables in a more generic way.

So, I'd be more in favor of keeping 

```.env
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=
```

rather than 

```.env
SES_ACCESS_KEY_ID=
SES_SECRET_ACCESS_KEY=
SES_REGION=
```


That way, these same variables can be used directly in the configuration of other things, like Drive for example. Without having to rename `SES_ACCESS_KEY_ID` to `AWS_ACCESS_KEY_ID` and so on. Because you probably use the same keys

**Comment by memsbdm** [comment]
I'd thought about it, but I thought it might be confusing if some people were using several services with different keys.
Nevermind, I updated the PR with `AWS_`!

**Comment by memsbdm** [comment]
Hey @Julien-R44 can you merge the PR? 😃

**Comment by Julien-R44** [comment]
Done! Thanks for fixing that
